<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>async - await</title>
  </head>
  <body>
    <h1>async - await</h1>
    <script>
      function cuadradoPromise(value) {
        //Las promesas devuelven un objeto , resolve o reject
        //validando y generando el reject o resolviendo el error o errores
        if (typeof value !== "number")
          return Promise.reject(
            `Error , el valor ${value} ingresado no es un numero`
          );

        //En caso de que sea del tipo correcto el valor
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            resolve({
              value, //como la propiedad y el valor tienen el mismo nombre se puede colocar solo el nonmbre
              result: value * value, //resultado si tiene exito
            });
          }, 0 | (Math.random() * 1000));
        });
      }

      //Funcion asincrona declarada
      //aqui ya se pueden comenzar a resolver las solicitudes asyncronas , que normalmente viene de una promesa
      async function funcionAsicronaDeclarada() {
        //trabajar manejo de errores
        try {
          //codigo q va a trabajar
          console.log("Inicio Async funtion");
          let obj = await cuadradoPromise(0); //con la palabra await le dice al codigo que tiene q esperar la respuestas para poder seguir el bloque
          console.log(`Async Funtion: ${obj.value}, ${obj.result}`);
          // Luegos de que ya nos de el error podemos seguir ejecutando una nueva operacion
          //la diferencias con las promesas es que aqui podemos usar varibles para ejecutar , y asi evitamos los .them
          obj = await cuadradoPromise(1);
          console.log(`Async Funtion: ${obj.value}, ${obj.result}`);
          obj = await cuadradoPromise(2);
          console.log(`Async Funtion: ${obj.value}, ${obj.result}`);
          obj = await cuadradoPromise("e"); //Error intencional
          console.log(`Async Funtion: ${obj.value}, ${obj.result}`);
          obj = await cuadradoPromise(4);
          console.log(`Async Funtion: ${obj.value}, ${obj.result}`);

          console.log("Fin de Async Funtion");
        } catch (err) {
          console.error(err);
        }
      }

      funcionAsicronaDeclarada();

      //funcion Async expresada - arrow funtion
      const funcionAsicronaExpresada = async () => {
        try {
          //codigo q va a trabajar
          console.log("Inicio Async funtion");
          let obj = await cuadradoPromise(0); //con la palabra await le dice al codigo que tiene q esperar la respuestas para poder seguir el bloque
          console.log(`Async Funtion: ${obj.value}, ${obj.result}`);
          // Luegos de que ya nos de el error podemos seguir ejecutando una nueva operacion
          //la diferencias con las promesas es que aqui podemos usar varibles para ejecutar , y asi evitamos los .them
          obj = await cuadradoPromise(5);
          console.log(`Async Funtion: ${obj.value}, ${obj.result}`);
          obj = await cuadradoPromise(6);
          console.log(`Async Funtion: ${obj.value}, ${obj.result}`);
          obj = await cuadradoPromise(7);
          console.log(`Async Funtion: ${obj.value}, ${obj.result}`);
          obj = await cuadradoPromise("e");
          console.log(`Async Funtion: ${obj.value}, ${obj.result}`);

          console.log("Fin de Async Funtion Expresada");
        } catch (err) {
          console.error(err);
        }
      };

      funcionAsicronaExpresada();
    </script>
  </body>
</html>
